In [1]:
from sklearn.datasets import load_wine

In [2]:
dataset = load_wine()
dataset

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 'frame': None,
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7'),
 'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:                    70.0 162.0    99.7  14.3\nTotal Phenols:                0.98  3.88    2.29  0.63\nFlavanoids:                   0.34  5.08    2.03  1.00\nNonflavanoid Phenols:         0.13  0.66    0.36  0.12\nProanthocyanins:              0.41  3.58    1.59  0.57\nColour Intensity:              1.3  13.0     5.1   2.3\nHue:                          0.48  1.71    0.96  0.23\nOD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\nProline:                       278  1680     746   315\n============================= ==== ===== ======= =====\n\n:Missing Attribute Values: None\n:Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners:\n\nForina, M. et al, PARVUS -\nAn Extendible Package for Data Exploration, Classification and Correlation.\nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science.\n\n.. dropdown:: References\n\n    (1) S. Aeberhard, D. Coomans and O. de Vel,\n    Comparison of Classifiers in High Dimensional Settings,\n    Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Technometrics).\n\n    The data was used with many others for comparing various\n    classifiers. The classes are separable, though only RDA\n    has achieved 100% correct classification.\n    (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))\n    (All results using the leave-one-out technique)\n\n    (2) S. Aeberhard, D. Coomans and O. de Vel,\n    "THE CLASSIFICATION PERFORMANCE OF RDA"\n    Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Journal of Chemometrics).\n',
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline']}

In [3]:
dataset.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [4]:
dataset.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [5]:
import pandas as pd
df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [6]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [7]:
df['category'] = dataset.target
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,category
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [8]:
df.shape

(178, 14)

In [9]:
X = dataset.data
y = dataset.target

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_test_split(X, y, test_size=0.3, random_state=5)
# 以下のようにrandom_stateを指定しない場合、実行毎に結果が異なります。
# train_test_split(X, y, test_size=0.3)

[array([[1.358e+01, 2.580e+00, 2.690e+00, ..., 7.400e-01, 1.800e+00,
         7.500e+02],
        [1.234e+01, 2.450e+00, 2.460e+00, ..., 8.000e-01, 3.380e+00,
         4.380e+02],
        [1.285e+01, 3.270e+00, 2.580e+00, ..., 8.700e-01, 2.110e+00,
         5.700e+02],
        ...,
        [1.225e+01, 3.880e+00, 2.200e+00, ..., 6.500e-01, 2.000e+00,
         8.550e+02],
        [1.277e+01, 3.430e+00, 1.980e+00, ..., 7.000e-01, 2.120e+00,
         3.720e+02],
        [1.229e+01, 3.170e+00, 2.210e+00, ..., 1.420e+00, 2.830e+00,
         4.060e+02]]),
 array([[1.387000e+01, 1.900000e+00, 2.800000e+00, 1.940000e+01,
         1.070000e+02, 2.950000e+00, 2.970000e+00, 3.700000e-01,
         1.760000e+00, 4.500000e+00, 1.250000e+00, 3.400000e+00,
         9.150000e+02],
        [1.311000e+01, 1.010000e+00, 1.700000e+00, 1.500000e+01,
         7.800000e+01, 2.980000e+00, 3.180000e+00, 2.600000e-01,
         2.280000e+00, 5.300000e+00, 1.120000e+00, 3.180000e+00,
         5.020000e+02],
        [1.437000e+01, 1.950000e+00, 2.500000e+00, 1.680000e+01,
         1.130000e+02, 3.850000e+00, 3.490000e+00, 2.400000e-01,
         2.180000e+00, 7.800000e+00, 8.600000e-01, 3.450000e+00,
         1.480000e+03],
        [1.383000e+01, 1.570000e+00, 2.620000e+00, 2.000000e+01,
         1.150000e+02, 2.950000e+00, 3.400000e+00, 4.000000e-01,
         1.720000e+00, 6.600000e+00, 1.130000e+00, 2.570000e+00,
         1.130000e+03],
        [1.349000e+01, 3.590000e+00, 2.190000e+00, 1.950000e+01,
         8.800000e+01, 1.620000e+00, 4.800000e-01, 5.800000e-01,
         8.800000e-01, 5.700000e+00, 8.100000e-01, 1.820000e+00,
         5.800000e+02],
        [1.345000e+01, 3.700000e+00, 2.600000e+00, 2.300000e+01,
         1.110000e+02, 1.700000e+00, 9.200000e-01, 4.300000e-01,
         1.460000e+00, 1.068000e+01, 8.500000e-01, 1.560000e+00,
         6.950000e+02],
        [1.410000e+01, 2.020000e+00, 2.400000e+00, 1.880000e+01,
         1.030000e+02, 2.750000e+00, 2.920000e+00, 3.200000e-01,
         2.380000e+00, 6.200000e+00, 1.070000e+00, 2.750000e+00,
         1.060000e+03],
        [1.356000e+01, 1.710000e+00, 2.310000e+00, 1.620000e+01,
         1.170000e+02, 3.150000e+00, 3.290000e+00, 3.400000e-01,
         2.340000e+00, 6.130000e+00, 9.500000e-01, 3.380000e+00,
         7.950000e+02],
        [1.247000e+01, 1.520000e+00, 2.200000e+00, 1.900000e+01,
         1.620000e+02, 2.500000e+00, 2.270000e+00, 3.200000e-01,
         3.280000e+00, 2.600000e+00, 1.160000e+00, 2.630000e+00,
         9.370000e+02],
        [1.305000e+01, 2.050000e+00, 3.220000e+00, 2.500000e+01,
         1.240000e+02, 2.630000e+00, 2.680000e+00, 4.700000e-01,
         1.920000e+00, 3.580000e+00, 1.130000e+00, 3.200000e+00,
         8.300000e+02],
        [1.422000e+01, 3.990000e+00, 2.510000e+00, 1.320000e+01,
         1.280000e+02, 3.000000e+00, 3.040000e+00, 2.000000e-01,
         2.080000e+00, 5.100000e+00, 8.900000e-01, 3.530000e+00,
         7.600000e+02],
        [1.356000e+01, 1.730000e+00, 2.460000e+00, 2.050000e+01,
         1.160000e+02, 2.960000e+00, 2.780000e+00, 2.000000e-01,
         2.450000e+00, 6.250000e+00, 9.800000e-01, 3.030000e+00,
         1.120000e+03],
        [1.270000e+01, 3.550000e+00, 2.360000e+00, 2.150000e+01,
         1.060000e+02, 1.700000e+00, 1.200000e+00, 1.700000e-01,
         8.400000e-01, 5.000000e+00, 7.800000e-01, 1.290000e+00,
         6.000000e+02],
        [1.260000e+01, 1.340000e+00, 1.900000e+00, 1.850000e+01,
         8.800000e+01, 1.450000e+00, 1.360000e+00, 2.900000e-01,
         1.350000e+00, 2.450000e+00, 1.040000e+00, 2.770000e+00,
         5.620000e+02],
        [1.352000e+01, 3.170000e+00, 2.720000e+00, 2.350000e+01,
         9.700000e+01, 1.550000e+00, 5.200000e-01, 5.000000e-01,
         5.500000e-01, 4.350000e+00, 8.900000e-01, 2.060000e+00,
         5.200000e+02],
        [1.339000e+01, 1.770000e+00, 2.620000e+00, 1.610000e+01,
         9.300000e+01, 2.850000e+00, 2.940000e+00, 3.400000e-01,
         1.450000e+00, 4.800000e+00, 9.200000e-01, 3.220000e+00,
         1.195000e+03],
        [1.243000e+01, 1.530000e+00, 2.290000e+00, 2.150000e+01,
         8.600000e+01, 2.740000e+00, 3.150000e+00, 3.900000e-01,
         1.770000e+00, 3.940000e+00, 6.900000e-01, 2.840000e+00,
         3.520000e+02],
        [1.324000e+01, 3.980000e+00, 2.290000e+00, 1.750000e+01,
         1.030000e+02, 2.640000e+00, 2.630000e+00, 3.200000e-01,
         1.660000e+00, 4.360000e+00, 8.200000e-01, 3.000000e+00,
         6.800000e+02],
        [1.184000e+01, 8.900000e-01, 2.580000e+00, 1.800000e+01,
         9.400000e+01, 2.200000e+00, 2.210000e+00, 2.200000e-01,
         2.350000e+00, 3.050000e+00, 7.900000e-01, 3.080000e+00,
         5.200000e+02],
        [1.293000e+01, 3.800000e+00, 2.650000e+00, 1.860000e+01,
         1.020000e+02, 2.410000e+00, 2.410000e+00, 2.500000e-01,
         1.980000e+00, 4.500000e+00, 1.030000e+00, 3.520000e+00,
         7.700000e+02],
        [1.422000e+01, 1.700000e+00, 2.300000e+00, 1.630000e+01,
         1.180000e+02, 3.200000e+00, 3.000000e+00, 2.600000e-01,
         2.030000e+00, 6.380000e+00, 9.400000e-01, 3.310000e+00,
         9.700000e+02],
        [1.329000e+01, 1.970000e+00, 2.680000e+00, 1.680000e+01,
         1.020000e+02, 3.000000e+00, 3.230000e+00, 3.100000e-01,
         1.660000e+00, 6.000000e+00, 1.070000e+00, 2.840000e+00,
         1.270000e+03],
        [1.196000e+01, 1.090000e+00, 2.300000e+00, 2.100000e+01,
         1.010000e+02, 3.380000e+00, 2.140000e+00, 1.300000e-01,
         1.650000e+00, 3.210000e+00, 9.900000e-01, 3.130000e+00,
         8.860000e+02],
        [1.269000e+01, 1.530000e+00, 2.260000e+00, 2.070000e+01,
         8.000000e+01, 1.380000e+00, 1.460000e+00, 5.800000e-01,
         1.620000e+00, 3.050000e+00, 9.600000e-01, 2.060000e+00,
         4.950000e+02],
        [1.252000e+01, 2.430000e+00, 2.170000e+00, 2.100000e+01,
         8.800000e+01, 2.550000e+00, 2.270000e+00, 2.600000e-01,
         1.220000e+00, 2.000000e+00, 9.000000e-01, 2.780000e+00,
         3.250000e+02],
        [1.208000e+01, 1.390000e+00, 2.500000e+00, 2.250000e+01,
         8.400000e+01, 2.560000e+00, 2.290000e+00, 4.300000e-01,
         1.040000e+00, 2.900000e+00, 9.300000e-01, 3.190000e+00,
         3.850000e+02],
        [1.377000e+01, 1.900000e+00, 2.680000e+00, 1.710000e+01,
         1.150000e+02, 3.000000e+00, 2.790000e+00, 3.900000e-01,
         1.680000e+00, 6.300000e+00, 1.130000e+00, 2.930000e+00,
         1.375000e+03],
        [1.286000e+01, 1.350000e+00, 2.320000e+00, 1.800000e+01,
         1.220000e+02, 1.510000e+00, 1.250000e+00, 2.100000e-01,
         9.400000e-01, 4.100000e+00, 7.600000e-01, 1.290000e+00,
         6.300000e+02],
        [1.340000e+01, 3.910000e+00, 2.480000e+00, 2.300000e+01,
         1.020000e+02, 1.800000e+00, 7.500000e-01, 4.300000e-01,
         1.410000e+00, 7.300000e+00, 7.000000e-01, 1.560000e+00,
         7.500000e+02],
        [1.388000e+01, 1.890000e+00, 2.590000e+00, 1.500000e+01,
         1.010000e+02, 3.250000e+00, 3.560000e+00, 1.700000e-01,
         1.700000e+00, 5.430000e+00, 8.800000e-01, 3.560000e+00,
         1.095000e+03],
        [1.237000e+01, 1.630000e+00, 2.300000e+00, 2.450000e+01,
         8.800000e+01, 2.220000e+00, 2.450000e+00, 4.000000e-01,
         1.900000e+00, 2.120000e+00, 8.900000e-01, 2.780000e+00,
         3.420000e+02],
        [1.367000e+01, 1.250000e+00, 1.920000e+00, 1.800000e+01,
         9.400000e+01, 2.100000e+00, 1.790000e+00, 3.200000e-01,
         7.300000e-01, 3.800000e+00, 1.230000e+00, 2.460000e+00,
         6.300000e+02],
        [1.285000e+01, 1.600000e+00, 2.520000e+00, 1.780000e+01,
         9.500000e+01, 2.480000e+00, 2.370000e+00, 2.600000e-01,
         1.460000e+00, 3.930000e+00, 1.090000e+00, 3.630000e+00,
         1.015000e+03],
        [1.320000e+01, 1.780000e+00, 2.140000e+00, 1.120000e+01,
         1.000000e+02, 2.650000e+00, 2.760000e+00, 2.600000e-01,
         1.280000e+00, 4.380000e+00, 1.050000e+00, 3.400000e+00,
         1.050000e+03],
        [1.316000e+01, 3.570000e+00, 2.150000e+00, 2.100000e+01,
         1.020000e+02, 1.500000e+00, 5.500000e-01, 4.300000e-01,
         1.300000e+00, 4.000000e+00, 6.000000e-01, 1.680000e+00,
         8.300000e+02],
        [1.317000e+01, 2.590000e+00, 2.370000e+00, 2.000000e+01,
         1.200000e+02, 1.650000e+00, 6.800000e-01, 5.300000e-01,
         1.460000e+00, 9.300000e+00, 6.000000e-01, 1.620000e+00,
         8.400000e+02],
        [1.374000e+01, 1.670000e+00, 2.250000e+00, 1.640000e+01,
         1.180000e+02, 2.600000e+00, 2.900000e+00, 2.100000e-01,
         1.620000e+00, 5.850000e+00, 9.200000e-01, 3.200000e+00,
         1.060000e+03],
        [1.293000e+01, 2.810000e+00, 2.700000e+00, 2.100000e+01,
         9.600000e+01, 1.540000e+00, 5.000000e-01, 5.300000e-01,
         7.500000e-01, 4.600000e+00, 7.700000e-01, 2.310000e+00,
         6.000000e+02],
        [1.332000e+01, 3.240000e+00, 2.380000e+00, 2.150000e+01,
         9.200000e+01, 1.930000e+00, 7.600000e-01, 4.500000e-01,
         1.250000e+00, 8.420000e+00, 5.500000e-01, 1.620000e+00,
         6.500000e+02],
        [1.272000e+01, 1.810000e+00, 2.200000e+00, 1.880000e+01,
         8.600000e+01, 2.200000e+00, 2.530000e+00, 2.600000e-01,
         1.770000e+00, 3.900000e+00, 1.160000e+00, 3.140000e+00,
         7.140000e+02],
        [1.164000e+01, 2.060000e+00, 2.460000e+00, 2.160000e+01,
         8.400000e+01, 1.950000e+00, 1.690000e+00, 4.800000e-01,
         1.350000e+00, 2.800000e+00, 1.000000e+00, 2.750000e+00,
         6.800000e+02],
        [1.264000e+01, 1.360000e+00, 2.020000e+00, 1.680000e+01,
         1.000000e+02, 2.020000e+00, 1.410000e+00, 5.300000e-01,
         6.200000e-01, 5.750000e+00, 9.800000e-01, 1.590000e+00,
         4.500000e+02],
        [1.225000e+01, 4.720000e+00, 2.540000e+00, 2.100000e+01,
         8.900000e+01, 1.380000e+00, 4.700000e-01, 5.300000e-01,
         8.000000e-01, 3.850000e+00, 7.500000e-01, 1.270000e+00,
         7.200000e+02],
        [1.438000e+01, 3.590000e+00, 2.280000e+00, 1.600000e+01,
         1.020000e+02, 3.250000e+00, 3.170000e+00, 2.700000e-01,
         2.190000e+00, 4.900000e+00, 1.040000e+00, 3.440000e+00,
         1.065000e+03],
        [1.277000e+01, 2.390000e+00, 2.280000e+00, 1.950000e+01,
         8.600000e+01, 1.390000e+00, 5.100000e-01, 4.800000e-01,
         6.400000e-01, 9.899999e+00, 5.700000e-01, 1.630000e+00,
         4.700000e+02],
        [1.237000e+01, 1.130000e+00, 2.160000e+00, 1.900000e+01,
         8.700000e+01, 3.500000e+00, 3.100000e+00, 1.900000e-01,
         1.870000e+00, 4.450000e+00, 1.220000e+00, 2.870000e+00,
         4.200000e+02],
        [1.305000e+01, 1.730000e+00, 2.040000e+00, 1.240000e+01,
         9.200000e+01, 2.720000e+00, 3.270000e+00, 1.700000e-01,
         2.910000e+00, 7.200000e+00, 1.120000e+00, 2.910000e+00,
         1.150000e+03],
        [1.296000e+01, 3.450000e+00, 2.350000e+00, 1.850000e+01,
         1.060000e+02, 1.390000e+00, 7.000000e-01, 4.000000e-01,
         9.400000e-01, 5.280000e+00, 6.800000e-01, 1.750000e+00,
         6.750000e+02],
        [1.375000e+01, 1.730000e+00, 2.410000e+00, 1.600000e+01,
         8.900000e+01, 2.600000e+00, 2.760000e+00, 2.900000e-01,
         1.810000e+00, 5.600000e+00, 1.150000e+00, 2.900000e+00,
         1.320000e+03],
        [1.229000e+01, 1.410000e+00, 1.980000e+00, 1.600000e+01,
         8.500000e+01, 2.550000e+00, 2.500000e+00, 2.900000e-01,
         1.770000e+00, 2.900000e+00, 1.230000e+00, 2.740000e+00,
         4.280000e+02],
        [1.383000e+01, 1.650000e+00, 2.600000e+00, 1.720000e+01,
         9.400000e+01, 2.450000e+00, 2.990000e+00, 2.200000e-01,
         2.290000e+00, 5.600000e+00, 1.240000e+00, 3.370000e+00,
         1.265000e+03],
        [1.229000e+01, 2.830000e+00, 2.220000e+00, 1.800000e+01,
         8.800000e+01, 2.450000e+00, 2.250000e+00, 2.500000e-01,
         1.990000e+00, 2.150000e+00, 1.150000e+00, 3.300000e+00,
         2.900000e+02],
        [1.237000e+01, 1.070000e+00, 2.100000e+00, 1.850000e+01,
         8.800000e+01, 3.520000e+00, 3.750000e+00, 2.400000e-01,
         1.950000e+00, 4.500000e+00, 1.040000e+00, 2.770000e+00,
         6.600000e+02],
        [1.364000e+01, 3.100000e+00, 2.560000e+00, 1.520000e+01,
         1.160000e+02, 2.700000e+00, 3.030000e+00, 1.700000e-01,
         1.660000e+00, 5.100000e+00, 9.600000e-01, 3.360000e+00,
         8.450000e+02]]),
 array([2, 1, 2, 1, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0, 0, 1, 2, 1, 1, 2, 2, 2,
        1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2, 2,
        2, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 2, 0, 2, 0,
        2, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 0, 2, 0,
        1, 0, 0, 2, 1, 1, 2, 0, 0, 0, 2, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1,
        0, 0, 1, 1, 2, 0, 2, 1, 2, 0, 1, 2, 1, 1]),
 array([0, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0,
        1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2, 0,
        2, 1, 0, 2, 0, 1, 0, 1, 1, 0])]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [13]:
print(X.shape, X_train.shape, X_test.shape, y.shape, y_train.shape, y_test.shape)

(178, 13) (124, 13) (54, 13) (178,) (124,) (54,)

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
model = DecisionTreeClassifier(random_state=3)
# 以下のようにrandom_stateを指定しない場合、最終的に生成される予測モデルが実行毎に異なる可能性があります。これは、モデルの評価結果や予測結果が実行毎に変わってしまう可能性があること意味します。
# model = DecisionTreeClassifier()

In [16]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=3)

In [17]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0,
       2, 1, 0, 2, 0, 1, 0, 1, 1, 0])

In [18]:
y_test

array([0, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2, 0,
       2, 1, 0, 2, 0, 1, 0, 1, 1, 0])

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
accuracy_score(y_test, y_pred)

0.9259259259259259

In [21]:
model.score(X_test, y_test)

0.9259259259259259

In [22]:
import numpy as np

X_real = np.array([
    [13, 1.6, 2.2, 16, 118, 2.6, 2.9, 0.21, 1.6, 5.8, 0.92, 3.2, 1011],
    [12, 2.8, 2.2, 18, 100, 2.5, 2.3, 0.25, 2.0, 2.2, 1.15, 3.3, 1000],
    [14, 4.1, 2.7, 24, 101, 1.6, 0.7, 0.53, 1.4, 9.4, 0.61, 1.6, 560]])

In [23]:
model.predict(X_real)

array([0, 1, 2])

In [27]:
#kadai_008
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

dataset = load_wine()
X = dataset.data
y = dataset.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=5
)

model = DecisionTreeClassifier(random_state=3)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=dataset.target_names))

Accuracy: 0.9259259259259259

Classification Report:
               precision    recall  f1-score   support

     class_0       0.95      0.91      0.93        23
     class_1       0.89      0.89      0.89        18
     class_2       0.93      1.00      0.96        13

    accuracy                           0.93        54
   macro avg       0.92      0.93      0.93        54
weighted avg       0.93      0.93      0.93        54